using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PauseMenuNew : MonoBehaviour
{

    public static bool GameIsPause = false;
    public GameObject pauseMenuUI;

    // Update is called once per frame
    private void Start()
    {
        Resume();
    }
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Escape))
        {
            if (GameIsPause)
            {
                Resume();
            }
            else
            {
                Pause();
            }
        }
    }
    void Resume()
    {
        pauseMenuUI.SetActive(false);
        Time.timeScale = 1f;
        GameIsPause = false;
    }
    void Pause()
    {
        pauseMenuUI.SetActive(true);
        Time.timeScale = 0f;
        GameIsPause = true;
    }
}
